baseURL = 'https://yourusername.github.io/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'PaperMod'

# 启用Emoji支持
enableEmoji = true

# 作者信息
[author]
  name = "你的名字"
  
# 菜单配置
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
    
# 主题相关参数
[params]
  # 主页信息
  title = "我的博客"
  description = "分享我的想法和经验"
  
  # 显示文章的阅读时间
  ShowReadingTime = true
  
  # 显示分享按钮
  ShowShareButtons = true
  
  # 显示文章目录
  ShowToc = true
  
  # 启用代码复制按钮
  ShowCodeCopyButtons = true
  
  # 主页模式设置为个人资料模式
  profileMode = { enabled = false }
  
  # 默认主题模式 (auto, light, dark)
  defaultTheme = "auto"
  
  # 显示文章的返回顶部按钮
  ShowPostNavLinks = true
